package app.singular.client.ui

/**
 * The vendored emoji set.
 *
 * A curated list rather than the full Unicode emoji catalogue (3,700+): this is a chat picker,
 * and everything past the first few hundred per category is a flag nobody has ever sent.
 * Curating also keeps the search index small enough to filter synchronously on every
 * keystroke, which is what makes the search box feel instant.
 *
 * Shortcodes follow the CLDR/emoji-test naming (`:smile:` means what it means everywhere that
 * supports shortcodes), so muscle memory transfers from Discord and Slack.
 */

enum class EmojiCategory(val label: String) {
    RECENT("Recently used"),
    SMILEYS("Smileys & people"),
    ANIMALS("Animals & nature"),
    FOOD("Food & drink"),
    ACTIVITY("Activity"),
    TRAVEL("Travel & places"),
    OBJECTS("Objects"),
    SYMBOLS("Symbols"),
}

data class EmojiEntry(val emoji: String, val name: String)

/** Every category in display order. RECENT is first only in the UI, not in the data. */
private val CATEGORY_ORDER = listOf(
    EmojiCategory.SMILEYS,
    EmojiCategory.ANIMALS,
    EmojiCategory.FOOD,
    EmojiCategory.ACTIVITY,
    EmojiCategory.TRAVEL,
    EmojiCategory.OBJECTS,
    EmojiCategory.SYMBOLS,
)

/** The full pickable set, in category order. */
val ALL_EMOJI: List<EmojiEntry> = CATEGORY_ORDER.flatMap(::emojiFor)

/** [emoji] by shortcode, e.g. "smile" -> "😃". */
val EMOJI_BY_NAME: Map<String, String> = ALL_EMOJI.associate { it.name to it.emoji }

fun emojiFor(category: EmojiCategory): List<EmojiEntry> = when (category) {
    EmojiCategory.RECENT -> emptyList()   // populated at runtime, not a static list
    EmojiCategory.SMILEYS -> SMILEYS
    EmojiCategory.ANIMALS -> ANIMALS
    EmojiCategory.FOOD -> FOOD
    EmojiCategory.ACTIVITY -> ACTIVITY
    EmojiCategory.TRAVEL -> TRAVEL
    EmojiCategory.OBJECTS -> OBJECTS
    EmojiCategory.SYMBOLS -> SYMBOLS
}

/**
 * Search: shortcode prefix first, then word-part. Synchronous by design — a few hundred
 * entries scan faster than any index's lookup overhead.
 */
fun searchEmoji(query: String, limit: Int = 48): List<EmojiEntry> {
    val q = query.trim().lowercase()
    if (q.isEmpty()) return emptyList()
    return ALL_EMOJI
        .mapNotNull { entry ->
            when {
                entry.name.startsWith(q) -> 0
                entry.name.contains(q) -> 1
                else -> null
            }?.let { rank -> rank to entry }
        }
        .sortedWith(compareBy({ it.first }, { it.second.name }))
        .take(limit)
        .map { it.second }
}

/**
 * The one-tap reaction row — Discord's default set, close enough. Separate from the grid
 * because what people react with skews far harder toward the affirmative faces than what the
 * grid starts with.
 */
val QUICK_REACTIONS: List<String> = listOf(
    "👍", "👎", "❤️", "😂", "😮", "😢", "🎉", "🔥",
)

private val SMILEYS = listOf(
    EmojiEntry("😀", "grinning"),
    EmojiEntry("😃", "smile"),
    EmojiEntry("😄", "smiley"),
    EmojiEntry("😁", "grin"),
    EmojiEntry("😆", "laughing"),
    EmojiEntry("😅", "sweat_smile"),
    EmojiEntry("🤣", "rofl"),
    EmojiEntry("😂", "joy"),
    EmojiEntry("🙂", "slightly_smiling"),
    EmojiEntry("🙃", "upside_down"),
    EmojiEntry("😉", "wink"),
    EmojiEntry("😊", "blush"),
    EmojiEntry("😇", "innocent"),
    EmojiEntry("🥰", "smiling_hearts"),
    EmojiEntry("😍", "heart_eyes"),
    EmojiEntry("🤩", "star_struck"),
    EmojiEntry("😘", "kissing_heart"),
    EmojiEntry("😋", "yum"),
    EmojiEntry("😛", "stuck_out_tongue"),
    EmojiEntry("😜", "tongue_wink"),
    EmojiEntry("🤪", "zany"),
    EmojiEntry("😝", "tongue_closed_eyes"),
    EmojiEntry("🤗", "hug"),
    EmojiEntry("🤭", "hand_over_mouth"),
    EmojiEntry("🤫", "shush"),
    EmojiEntry("🤔", "thinking"),
    EmojiEntry("🤨", "raised_eyebrow"),
    EmojiEntry("😐", "neutral"),
    EmojiEntry("😑", "expressionless"),
    EmojiEntry("😶", "no_mouth"),
    EmojiEntry("😏", "smirk"),
    EmojiEntry("😒", "unamused"),
    EmojiEntry("🙄", "rolling_eyes"),
    EmojiEntry("😬", "grimacing"),
    EmojiEntry("🤥", "lying"),
    EmojiEntry("😌", "relieved"),
    EmojiEntry("😔", "pensive"),
    EmojiEntry("😪", "sleepy"),
    EmojiEntry("🤤", "drool"),
    EmojiEntry("😴", "sleeping"),
    EmojiEntry("😷", "mask"),
    EmojiEntry("🤒", "thermometer"),
    EmojiEntry("🤕", "bandage"),
    EmojiEntry("🤢", "nauseated"),
    EmojiEntry("🤮", "vomit"),
    EmojiEntry("🤧", "sneeze"),
    EmojiEntry("🥵", "hot"),
    EmojiEntry("🥶", "cold"),
    EmojiEntry("🥴", "woozy"),
    EmojiEntry("😵", "dizzy"),
    EmojiEntry("🤯", "mind_blown"),
    EmojiEntry("🤠", "cowboy"),
    EmojiEntry("🥳", "party"),
    EmojiEntry("🥸", "disguise"),
    EmojiEntry("😎", "sunglasses"),
    EmojiEntry("🤓", "nerd"),
    EmojiEntry("🧐", "monocle"),
    EmojiEntry("😕", "confused"),
    EmojiEntry("😟", "worried"),
    EmojiEntry("🙁", "frown"),
    EmojiEntry("😮", "open_mouth"),
    EmojiEntry("😯", "hushed"),
    EmojiEntry("😲", "astonished"),
    EmojiEntry("😳", "flushed"),
    EmojiEntry("🥺", "pleading"),
    EmojiEntry("😦", "anguish"),
    EmojiEntry("😨", "fearful"),
    EmojiEntry("😰", "cold_sweat"),
    EmojiEntry("😥", "sad_relieved"),
    EmojiEntry("😢", "cry"),
    EmojiEntry("😭", "sob"),
    EmojiEntry("😱", "scream"),
    EmojiEntry("😖", "confounded"),
    EmojiEntry("😣", "persevere"),
    EmojiEntry("😞", "disappointed"),
    EmojiEntry("😓", "sweat"),
    EmojiEntry("😩", "weary"),
    EmojiEntry("😫", "tired"),
    EmojiEntry("🥱", "yawn"),
    EmojiEntry("😤", "triumph"),
    EmojiEntry("😡", "rage"),
    EmojiEntry("😠", "angry"),
    EmojiEntry("🤬", "cursing"),
    EmojiEntry("😈", "smiling_imp"),
    EmojiEntry("👿", "imp"),
    EmojiEntry("💀", "skull"),
    EmojiEntry("💩", "poop"),
    EmojiEntry("🤡", "clown"),
    EmojiEntry("👻", "ghost"),
    EmojiEntry("👽", "alien"),
    EmojiEntry("🤖", "robot"),
    EmojiEntry("😺", "smiley_cat"),
    EmojiEntry("😹", "joy_cat"),
    EmojiEntry("😻", "heart_eyes_cat"),
    EmojiEntry("😼", "smirk_cat"),
    EmojiEntry("🙀", "scream_cat"),
    EmojiEntry("😿", "crying_cat"),
    EmojiEntry("😾", "pouting_cat"),
    EmojiEntry("🙈", "see_no_evil"),
    EmojiEntry("🙉", "hear_no_evil"),
    EmojiEntry("🙊", "speak_no_evil"),

    // Gestures and people — one tab, like Discord's.
    EmojiEntry("👋", "wave"),
    EmojiEntry("🤚", "raised_back_of_hand"),
    EmojiEntry("✋", "raised_hand"),
    EmojiEntry("🖖", "vulcan_salute"),
    EmojiEntry("👌", "ok_hand"),
    EmojiEntry("🤌", "pinched_fingers"),
    EmojiEntry("🤏", "pinching_hand"),
    EmojiEntry("✌️", "peace"),
    EmojiEntry("🤞", "crossed_fingers"),
    EmojiEntry("🤟", "love_you"),
    EmojiEntry("🤘", "metal"),
    EmojiEntry("🤙", "call_me"),
    EmojiEntry("👈", "point_left"),
    EmojiEntry("👉", "point_right"),
    EmojiEntry("👆", "point_up"),
    EmojiEntry("👇", "point_down"),
    EmojiEntry("👍", "thumbs_up"),
    EmojiEntry("👎", "thumbs_down"),
    EmojiEntry("✊", "fist"),
    EmojiEntry("👊", "punch"),
    EmojiEntry("🤛", "fist_left"),
    EmojiEntry("🤜", "fist_right"),
    EmojiEntry("👏", "clap"),
    EmojiEntry("🙌", "raised_hands"),
    EmojiEntry("🤝", "handshake"),
    EmojiEntry("🙏", "pray"),
    EmojiEntry("✍️", "writing"),
    EmojiEntry("💅", "nail_polish"),
    EmojiEntry("🤳", "selfie"),
    EmojiEntry("💪", "muscle"),
    EmojiEntry("👀", "eyes"),
    EmojiEntry("👁️", "eye"),
    EmojiEntry("👅", "tongue"),
    EmojiEntry("👄", "lips"),
    EmojiEntry("👶", "baby"),
    EmojiEntry("🧒", "child"),
    EmojiEntry("👦", "boy"),
    EmojiEntry("👧", "girl"),
    EmojiEntry("👨", "man"),
    EmojiEntry("👩", "woman"),
    EmojiEntry("🧓", "older"),
    EmojiEntry("👴", "old_man"),
    EmojiEntry("👵", "old_woman"),
    EmojiEntry("🙅", "no_gesture"),
    EmojiEntry("🙆", "ok_gesture"),
    EmojiEntry("🙋", "raising_hand"),
    EmojiEntry("🙇", "bow"),
    EmojiEntry("🤦", "facepalm"),
    EmojiEntry("🤷", "shrug"),
    EmojiEntry("👮", "cop"),
    EmojiEntry("🕵️", "detective"),
    EmojiEntry("👷", "builder"),
    EmojiEntry("🤴", "prince"),
    EmojiEntry("👸", "princess"),
    EmojiEntry("🤵", "tuxedo"),
    EmojiEntry("👰", "veil"),
    EmojiEntry("🤰", "pregnant"),
    EmojiEntry("👼", "angel"),
    EmojiEntry("🎅", "santa"),
    EmojiEntry("🦸", "hero"),
    EmojiEntry("🦹", "villain"),
    EmojiEntry("🧙", "mage"),
    EmojiEntry("🧚", "fairy"),
    EmojiEntry("🧛", "vampire"),
    EmojiEntry("🧜", "merperson"),
    EmojiEntry("🧝", "elf"),
    EmojiEntry("🧞", "genie"),
    EmojiEntry("🧟", "zombie"),
    EmojiEntry("🚶", "walking"),
    EmojiEntry("🏃", "running"),
    EmojiEntry("💃", "dancing_woman"),
    EmojiEntry("🕺", "dancing_man"),
    EmojiEntry("🧘", "lotus"),
    EmojiEntry("💋", "kiss"),
    EmojiEntry("💌", "love_letter"),
    EmojiEntry("💔", "broken_heart"),
    EmojiEntry("❤️", "heart"),
    EmojiEntry("🧡", "orange_heart"),
    EmojiEntry("💛", "yellow_heart"),
    EmojiEntry("💚", "green_heart"),
    EmojiEntry("💙", "blue_heart"),
    EmojiEntry("💜", "purple_heart"),
    EmojiEntry("🖤", "black_heart"),
    EmojiEntry("🤍", "white_heart"),
    EmojiEntry("🤎", "brown_heart"),
    EmojiEntry("💯", "100"),
    EmojiEntry("💢", "anger"),
    EmojiEntry("💥", "boom"),
    EmojiEntry("💦", "sweat_drops"),
    EmojiEntry("💨", "dash"),
    EmojiEntry("💬", "speech"),
    EmojiEntry("💭", "thought"),
    EmojiEntry("💤", "zzz"),
)

private val ANIMALS = listOf(
    EmojiEntry("🐵", "monkey_face"),
    EmojiEntry("🐒", "monkey"),
    EmojiEntry("🦍", "gorilla"),
    EmojiEntry("🐶", "dog_face"),
    EmojiEntry("🐕", "dog"),
    EmojiEntry("🐩", "poodle"),
    EmojiEntry("🐺", "wolf"),
    EmojiEntry("🦊", "fox"),
    EmojiEntry("🦝", "raccoon"),
    EmojiEntry("🐱", "cat_face"),
    EmojiEntry("🐈", "cat"),
    EmojiEntry("🦁", "lion"),
    EmojiEntry("🐯", "tiger_face"),
    EmojiEntry("🐅", "tiger"),
    EmojiEntry("🐆", "leopard"),
    EmojiEntry("🐴", "horse_face"),
    EmojiEntry("🐎", "horse"),
    EmojiEntry("🦄", "unicorn"),
    EmojiEntry("🦓", "zebra"),
    EmojiEntry("🦌", "deer"),
    EmojiEntry("🐮", "cow_face"),
    EmojiEntry("🐷", "pig_face"),
    EmojiEntry("🐗", "boar"),
    EmojiEntry("🐽", "pig_nose"),
    EmojiEntry("🐏", "ram"),
    EmojiEntry("🐑", "sheep"),
    EmojiEntry("🐐", "goat"),
    EmojiEntry("🐪", "camel"),
    EmojiEntry("🦙", "llama"),
    EmojiEntry("🦒", "giraffe"),
    EmojiEntry("🐘", "elephant"),
    EmojiEntry("🦏", "rhino"),
    EmojiEntry("🦛", "hippo"),
    EmojiEntry("🐭", "mouse_face"),
    EmojiEntry("🐹", "hamster"),
    EmojiEntry("🐰", "rabbit_face"),
    EmojiEntry("🐿️", "chipmunk"),
    EmojiEntry("🦫", "beaver"),
    EmojiEntry("🦔", "hedgehog"),
    EmojiEntry("🦇", "bat"),
    EmojiEntry("🐻", "bear"),
    EmojiEntry("🐨", "koala"),
    EmojiEntry("🐼", "panda"),
    EmojiEntry("🦥", "sloth"),
    EmojiEntry("🦦", "otter"),
    EmojiEntry("🦨", "skunk"),
    EmojiEntry("🦘", "kangaroo"),
    EmojiEntry("🦡", "badger"),
    EmojiEntry("🐾", "paws"),
    EmojiEntry("🦃", "turkey"),
    EmojiEntry("🐔", "chicken"),
    EmojiEntry("🐓", "rooster"),
    EmojiEntry("🐣", "hatching"),
    EmojiEntry("🐤", "chick"),
    EmojiEntry("🐦", "bird"),
    EmojiEntry("🐧", "penguin"),
    EmojiEntry("🕊️", "dove"),
    EmojiEntry("🦅", "eagle"),
    EmojiEntry("🦆", "duck"),
    EmojiEntry("🦢", "swan"),
    EmojiEntry("🦉", "owl"),
    EmojiEntry("🦩", "flamingo"),
    EmojiEntry("🦚", "peacock"),
    EmojiEntry("🦜", "parrot"),
    EmojiEntry("🐸", "frog"),
    EmojiEntry("🐊", "crocodile"),
    EmojiEntry("🐢", "turtle"),
    EmojiEntry("🦎", "lizard"),
    EmojiEntry("🐍", "snake"),
    EmojiEntry("🐲", "dragon_face"),
    EmojiEntry("🐉", "dragon"),
    EmojiEntry("🦕", "sauropod"),
    EmojiEntry("🦖", "trex"),
    EmojiEntry("🐳", "whale_spout"),
    EmojiEntry("🐋", "whale"),
    EmojiEntry("🐬", "dolphin"),
    EmojiEntry("🦭", "seal"),
    EmojiEntry("🐟", "fish"),
    EmojiEntry("🐠", "tropical_fish"),
    EmojiEntry("🐡", "blowfish"),
    EmojiEntry("🦈", "shark"),
    EmojiEntry("🐙", "octopus"),
    EmojiEntry("🐚", "shell"),
    EmojiEntry("🦀", "crab"),
    EmojiEntry("🦞", "lobster"),
    EmojiEntry("🦐", "shrimp"),
    EmojiEntry("🦑", "squid"),
    EmojiEntry("🐌", "snail"),
    EmojiEntry("🦋", "butterfly"),
    EmojiEntry("🐛", "bug"),
    EmojiEntry("🐜", "ant"),
    EmojiEntry("🐝", "bee"),
    EmojiEntry("🐞", "ladybug"),
    EmojiEntry("🦗", "cricket"),
    EmojiEntry("🕷️", "spider"),
    EmojiEntry("🦂", "scorpion"),
    EmojiEntry("🦟", "mosquito"),
    EmojiEntry("🪰", "fly"),
    EmojiEntry("🪱", "worm"),
    EmojiEntry("🦠", "microbe"),

    // Plants close out the living world.
    EmojiEntry("💐", "bouquet"),
    EmojiEntry("🌸", "cherry_blossom"),
    EmojiEntry("💮", "white_flower"),
    EmojiEntry("🌹", "rose"),
    EmojiEntry("🥀", "wilted"),
    EmojiEntry("🌺", "hibiscus"),
    EmojiEntry("🌻", "sunflower"),
    EmojiEntry("🌼", "blossom"),
    EmojiEntry("🌷", "tulip"),
    EmojiEntry("🌱", "seedling"),
    EmojiEntry("🪴", "potted_plant"),
    EmojiEntry("🌲", "evergreen"),
    EmojiEntry("🌳", "tree"),
    EmojiEntry("🌴", "palm"),
    EmojiEntry("🌵", "cactus"),
    EmojiEntry("🌾", "rice"),
    EmojiEntry("🌿", "herb"),
    EmojiEntry("🍀", "clover"),
    EmojiEntry("🍁", "maple_leaf"),
    EmojiEntry("🍂", "leaves"),
    EmojiEntry("🍃", "leaf_wind"),
)

private val FOOD = listOf(
    EmojiEntry("🍇", "grapes"),
    EmojiEntry("🍈", "melon"),
    EmojiEntry("🍉", "watermelon"),
    EmojiEntry("🍊", "tangerine"),
    EmojiEntry("🍋", "lemon"),
    EmojiEntry("🍌", "banana"),
    EmojiEntry("🍍", "pineapple"),
    EmojiEntry("🥭", "mango"),
    EmojiEntry("🍎", "apple"),
    EmojiEntry("🍏", "green_apple"),
    EmojiEntry("🍐", "pear"),
    EmojiEntry("🍑", "peach"),
    EmojiEntry("🍒", "cherries"),
    EmojiEntry("🍓", "strawberry"),
    EmojiEntry("🥝", "kiwi"),
    EmojiEntry("🍅", "tomato"),
    EmojiEntry("🥥", "coconut"),
    EmojiEntry("🥑", "avocado"),
    EmojiEntry("🍆", "eggplant"),
    EmojiEntry("🥔", "potato"),
    EmojiEntry("🥕", "carrot"),
    EmojiEntry("🌽", "corn"),
    EmojiEntry("🌶️", "pepper"),
    EmojiEntry("🥒", "cucumber"),
    EmojiEntry("🥬", "greens"),
    EmojiEntry("🥦", "broccoli"),
    EmojiEntry("🧄", "garlic"),
    EmojiEntry("🧅", "onion"),
    EmojiEntry("🍄", "mushroom"),
    EmojiEntry("🥜", "peanuts"),
    EmojiEntry("🌰", "chestnut"),
    EmojiEntry("🍞", "bread"),
    EmojiEntry("🥐", "croissant"),
    EmojiEntry("🥖", "baguette"),
    EmojiEntry("🥨", "pretzel"),
    EmojiEntry("🥯", "bagel"),
    EmojiEntry("🥞", "pancakes"),
    EmojiEntry("🧇", "waffle"),
    EmojiEntry("🧈", "butter"),
    EmojiEntry("🍳", "cooking"),
    EmojiEntry("🥚", "egg"),
    EmojiEntry("🧀", "cheese"),
    EmojiEntry("🍖", "meat_bone"),
    EmojiEntry("🍗", "poultry_leg"),
    EmojiEntry("🥩", "steak"),
    EmojiEntry("🥓", "bacon"),
    EmojiEntry("🍔", "burger"),
    EmojiEntry("🍟", "fries"),
    EmojiEntry("🍕", "pizza"),
    EmojiEntry("🌭", "hot_dog"),
    EmojiEntry("🥪", "sandwich"),
    EmojiEntry("🌮", "taco"),
    EmojiEntry("🌯", "burrito"),
    EmojiEntry("🥙", "flatbread"),
    EmojiEntry("🧆", "falafel"),
    EmojiEntry("🥘", "paella"),
    EmojiEntry("🍲", "stew"),
    EmojiEntry("🥣", "bowl_spoon"),
    EmojiEntry("🥗", "salad"),
    EmojiEntry("🍿", "popcorn"),
    EmojiEntry("🧂", "salt"),
    EmojiEntry("🥫", "can"),
    EmojiEntry("🍱", "bento"),
    EmojiEntry("🍘", "rice_cracker"),
    EmojiEntry("🍙", "rice_ball"),
    EmojiEntry("🍚", "rice_cooked"),
    EmojiEntry("🍛", "curry"),
    EmojiEntry("🍜", "noodles"),
    EmojiEntry("🍝", "spaghetti"),
    EmojiEntry("🍠", "sweet_potato"),
    EmojiEntry("🍢", "oden"),
    EmojiEntry("🍣", "sushi"),
    EmojiEntry("🍤", "shrimp_fried"),
    EmojiEntry("🍥", "fish_cake"),
    EmojiEntry("🥮", "moon_cake"),
    EmojiEntry("🍡", "dango"),
    EmojiEntry("🍧", "shaved_ice"),
    EmojiEntry("🍨", "ice_cream"),
    EmojiEntry("🍦", "soft_serve"),
    EmojiEntry("🥧", "pie"),
    EmojiEntry("🧁", "cupcake"),
    EmojiEntry("🍰", "cake_slice"),
    EmojiEntry("🎂", "birthday"),
    EmojiEntry("🍮", "custard"),
    EmojiEntry("🍭", "lollipop"),
    EmojiEntry("🍬", "candy"),
    EmojiEntry("🍫", "chocolate"),
    EmojiEntry("🍩", "donut"),
    EmojiEntry("🍪", "cookie"),
    EmojiEntry("🥛", "milk"),
    EmojiEntry("🍺", "beer"),
    EmojiEntry("🍻", "beers"),
    EmojiEntry("🥂", "champagne"),
    EmojiEntry("🍷", "wine"),
    EmojiEntry("🥃", "whisky"),
    EmojiEntry("🍸", "cocktail"),
    EmojiEntry("🍹", "tropical_drink"),
    EmojiEntry("🧃", "juice_box"),
    EmojiEntry("🥤", "soda"),
    EmojiEntry("🧋", "boba"),
    EmojiEntry("🍵", "tea"),
    EmojiEntry("☕", "coffee"),
    EmojiEntry("🫖", "teapot"),
    EmojiEntry("🧊", "ice_cube"),
    EmojiEntry("🥢", "chopsticks"),
    EmojiEntry("🍽️", "plate"),
    EmojiEntry("🍴", "fork_knife"),
    EmojiEntry("🥄", "spoon"),
    EmojiEntry("🔪", "knife"),
)

private val ACTIVITY = listOf(
    EmojiEntry("🎉", "tada"),
    EmojiEntry("🎊", "confetti"),
    EmojiEntry("🎈", "balloon"),
    EmojiEntry("🎁", "gift"),
    EmojiEntry("🎗️", "reminder_ribbon"),
    EmojiEntry("🎟️", "ticket"),
    EmojiEntry("🎫", "admission"),
    EmojiEntry("🎯", "dart"),
    EmojiEntry("🎱", "8ball"),
    EmojiEntry("🎲", "dice"),
    EmojiEntry("🧩", "puzzle"),
    EmojiEntry("🪀", "yo_yo"),
    EmojiEntry("🪁", "kite"),
    EmojiEntry("🎭", "theatre"),
    EmojiEntry("🖼️", "art"),
    EmojiEntry("🎨", "palette"),
    EmojiEntry("🧵", "thread"),
    EmojiEntry("🧶", "yarn"),
    EmojiEntry("🎼", "score"),
    EmojiEntry("🎤", "mic"),
    EmojiEntry("🎧", "headphones"),
    EmojiEntry("🎺", "trumpet"),
    EmojiEntry("🥁", "drum"),
    EmojiEntry("🎷", "saxophone"),
    EmojiEntry("🎸", "guitar"),
    EmojiEntry("🎹", "piano"),
    EmojiEntry("🎻", "violin"),
    EmojiEntry("🪕", "banjo"),
    EmojiEntry("🎮", "game_controller"),
    EmojiEntry("🕹️", "joystick"),
    EmojiEntry("♠️", "spades"),
    EmojiEntry("♥️", "hearts"),
    EmojiEntry("♦️", "diamonds"),
    EmojiEntry("♣️", "clubs"),
    EmojiEntry("🃏", "joker"),
    EmojiEntry("🥇", "gold"),
    EmojiEntry("🥈", "silver"),
    EmojiEntry("🥉", "bronze"),
    EmojiEntry("🏅", "medal"),
    EmojiEntry("🏆", "trophy"),
    EmojiEntry("⚽", "soccer"),
    EmojiEntry("⚾", "baseball"),
    EmojiEntry("🏀", "basketball"),
    EmojiEntry("🏐", "volleyball"),
    EmojiEntry("🏈", "football"),
    EmojiEntry("🎾", "tennis"),
    EmojiEntry("🥏", "frisbee"),
    EmojiEntry("🎳", "bowling"),
    EmojiEntry("🏏", "cricket_game"),
    EmojiEntry("🏑", "field_hockey"),
    EmojiEntry("🏒", "ice_hockey"),
    EmojiEntry("🏓", "ping_pong"),
    EmojiEntry("🏸", "badminton"),
    EmojiEntry("🥊", "boxing"),
    EmojiEntry("🥋", "martial_arts"),
    EmojiEntry("🥅", "goal"),
    EmojiEntry("⛳", "golf"),
    EmojiEntry("⛸️", "skate"),
    EmojiEntry("🎣", "fishing"),
    EmojiEntry("🎽", "jersey"),
    EmojiEntry("🎿", "skis"),
    EmojiEntry("🛷", "sled"),
    EmojiEntry("🥌", "curling"),
)

private val TRAVEL = listOf(
    EmojiEntry("🚗", "car"),
    EmojiEntry("🚕", "taxi"),
    EmojiEntry("🚙", "suv"),
    EmojiEntry("🚌", "bus"),
    EmojiEntry("🚑", "ambulance"),
    EmojiEntry("🚒", "fire_truck"),
    EmojiEntry("🚓", "police_car"),
    EmojiEntry("🚚", "truck"),
    EmojiEntry("🚜", "tractor"),
    EmojiEntry("🏎️", "race_car"),
    EmojiEntry("🏍️", "motorcycle"),
    EmojiEntry("🛵", "scooter"),
    EmojiEntry("🚲", "bike"),
    EmojiEntry("🛴", "kick_scooter"),
    EmojiEntry("🛹", "skateboard"),
    EmojiEntry("🚨", "siren"),
    EmojiEntry("🚦", "traffic_light"),
    EmojiEntry("🛑", "stop_sign"),
    EmojiEntry("🚧", "construction"),
    EmojiEntry("⚓", "anchor"),
    EmojiEntry("⛵", "sailboat"),
    EmojiEntry("🛶", "canoe"),
    EmojiEntry("🚤", "speedboat"),
    EmojiEntry("🛳️", "cruise"),
    EmojiEntry("⛴️", "ferry"),
    EmojiEntry("🚢", "ship"),
    EmojiEntry("✈️", "airplane"),
    EmojiEntry("🛫", "takeoff"),
    EmojiEntry("🛬", "landing"),
    EmojiEntry("🚀", "rocket"),
    EmojiEntry("🛸", "ufo"),
    EmojiEntry("🛰️", "satellite"),
    EmojiEntry("🚁", "helicopter"),
    EmojiEntry("🚂", "train_steam"),
    EmojiEntry("🚄", "train_bullet"),
    EmojiEntry("🚆", "train"),
    EmojiEntry("🚇", "metro"),
    EmojiEntry("🚉", "station"),
    EmojiEntry("🚊", "tram"),
    EmojiEntry("🏔️", "mountain_snow"),
    EmojiEntry("⛰️", "mountain"),
    EmojiEntry("🌋", "volcano"),
    EmojiEntry("🏕️", "camping"),
    EmojiEntry("🏖️", "beach"),
    EmojiEntry("🏜️", "desert"),
    EmojiEntry("🏝️", "island"),
    EmojiEntry("🏞️", "park"),
    EmojiEntry("🏟️", "stadium"),
    EmojiEntry("🏛️", "classical"),
    EmojiEntry("🏗️", "site"),
    EmojiEntry("🏠", "house"),
    EmojiEntry("🏡", "garden"),
    EmojiEntry("🏢", "office"),
    EmojiEntry("🏥", "hospital"),
    EmojiEntry("🏦", "bank"),
    EmojiEntry("🏨", "hotel"),
    EmojiEntry("🏪", "store"),
    EmojiEntry("🏫", "school"),
    EmojiEntry("🏭", "factory"),
    EmojiEntry("🏰", "castle"),
    EmojiEntry("💒", "wedding"),
    EmojiEntry("🗼", "tokyo_tower"),
    EmojiEntry("🗽", "liberty"),
    EmojiEntry("⛪", "church"),
    EmojiEntry("🕌", "mosque"),
    EmojiEntry("🛕", "temple"),
    EmojiEntry("🕍", "synagogue"),
    EmojiEntry("⛩️", "shrine"),
    EmojiEntry("🕋", "kaaba"),
    EmojiEntry("⛲", "fountain"),
    EmojiEntry("⛺", "tent"),
    EmojiEntry("🌁", "foggy"),
    EmojiEntry("🌃", "night"),
    EmojiEntry("🏙️", "cityscape"),
    EmojiEntry("🌅", "sunrise"),
    EmojiEntry("🌇", "sunset"),
    EmojiEntry("🌉", "bridge"),
    EmojiEntry("♨️", "hotsprings"),
    EmojiEntry("🎠", "carousel"),
    EmojiEntry("🎡", "ferris"),
    EmojiEntry("🎢", "coaster"),
    EmojiEntry("💈", "barber"),
    EmojiEntry("🎪", "circus"),
)

private val OBJECTS = listOf(
    EmojiEntry("⌚", "watch"),
    EmojiEntry("📱", "phone"),
    EmojiEntry("📲", "phone_arrow"),
    EmojiEntry("💻", "laptop"),
    EmojiEntry("⌨️", "keyboard"),
    EmojiEntry("🖥️", "monitor"),
    EmojiEntry("🖨️", "printer"),
    EmojiEntry("🖱️", "mouse"),
    EmojiEntry("💽", "minidisc"),
    EmojiEntry("💾", "floppy"),
    EmojiEntry("💿", "cd"),
    EmojiEntry("📀", "dvd"),
    EmojiEntry("📼", "vhs"),
    EmojiEntry("📷", "camera"),
    EmojiEntry("📸", "camera_flash"),
    EmojiEntry("📹", "video_camera"),
    EmojiEntry("🎥", "movie_camera"),
    EmojiEntry("📞", "receiver"),
    EmojiEntry("☎️", "telephone"),
    EmojiEntry("📺", "tv"),
    EmojiEntry("📻", "radio"),
    EmojiEntry("🎙️", "studio_mic"),
    EmojiEntry("⏰", "alarm"),
    EmojiEntry("⌛", "hourglass"),
    EmojiEntry("⏳", "hourglass_flow"),
    EmojiEntry("📡", "dish"),
    EmojiEntry("🔋", "battery"),
    EmojiEntry("🔌", "plug"),
    EmojiEntry("💡", "bulb"),
    EmojiEntry("🔦", "flashlight"),
    EmojiEntry("🕯️", "candle"),
    EmojiEntry("🧯", "extinguisher"),
    EmojiEntry("💸", "money_wings"),
    EmojiEntry("💵", "dollar"),
    EmojiEntry("💴", "yen"),
    EmojiEntry("💶", "euro"),
    EmojiEntry("💷", "pound"),
    EmojiEntry("🪙", "coin"),
    EmojiEntry("💰", "moneybag"),
    EmojiEntry("💳", "card"),
    EmojiEntry("💎", "gem"),
    EmojiEntry("⚖️", "scales"),
    EmojiEntry("🧰", "toolbox"),
    EmojiEntry("🔧", "wrench"),
    EmojiEntry("🔨", "hammer"),
    EmojiEntry("🛠️", "tools"),
    EmojiEntry("⚙️", "gear"),
    EmojiEntry("🧲", "magnet"),
    EmojiEntry("🔫", "pistol"),
    EmojiEntry("💣", "bomb"),
    EmojiEntry("🧨", "firework"),
    EmojiEntry("🪓", "axe"),
    EmojiEntry("🛡️", "shield"),
    EmojiEntry("⚰️", "coffin"),
    EmojiEntry("🔮", "crystal_ball"),
    EmojiEntry("🧿", "nazar"),
    EmojiEntry("🧳", "luggage"),
    EmojiEntry("🧴", "lotion"),
    EmojiEntry("🧷", "pin"),
    EmojiEntry("🧹", "broom"),
    EmojiEntry("🧺", "basket"),
    EmojiEntry("🧻", "paper_roll"),
    EmojiEntry("🪣", "bucket"),
    EmojiEntry("🧼", "soap"),
    EmojiEntry("🪥", "toothbrush"),
    EmojiEntry("🧽", "sponge"),
    EmojiEntry("🛒", "cart"),
    EmojiEntry("🧪", "test_tube"),
    EmojiEntry("🧫", "petri"),
    EmojiEntry("🧬", "dna"),
    EmojiEntry("🔬", "microscope"),
    EmojiEntry("🔭", "telescope"),
    EmojiEntry("💉", "syringe"),
    EmojiEntry("🩸", "blood"),
    EmojiEntry("💊", "pill"),
    EmojiEntry("🩹", "bandaid"),
    EmojiEntry("🩺", "stethoscope"),
    EmojiEntry("🚪", "door"),
    EmojiEntry("🛗", "elevator"),
    EmojiEntry("🪞", "mirror"),
    EmojiEntry("🪟", "window"),
    EmojiEntry("🛏️", "bed"),
    EmojiEntry("🛋️", "couch"),
    EmojiEntry("🪑", "chair"),
    EmojiEntry("🚽", "toilet"),
    EmojiEntry("🚿", "shower"),
    EmojiEntry("🛁", "bath"),
    EmojiEntry("🧸", "teddy"),
    EmojiEntry("🪆", "nesting_dolls"),
    EmojiEntry("🛍️", "shopping_bags"),
    EmojiEntry("🎀", "ribbon"),
    EmojiEntry("🪄", "wand"),
    EmojiEntry("🪅", "pinata"),
    EmojiEntry("🪩", "disco_ball"),
    EmojiEntry("🎰", "slots"),
    EmojiEntry("🎃", "pumpkin"),
    EmojiEntry("🎄", "tree_holiday"),
    EmojiEntry("🎆", "fireworks"),
    EmojiEntry("🎇", "sparkler"),
    EmojiEntry("✨", "sparkles"),
    EmojiEntry("🎋", "tanabata"),
    EmojiEntry("🎍", "bamboo"),
    EmojiEntry("🎎", "dolls"),
    EmojiEntry("🎏", "carp_flag"),
    EmojiEntry("🎐", "wind_chime"),
    EmojiEntry("🔑", "key"),
    EmojiEntry("🗝️", "old_key"),
)

private val SYMBOLS = listOf(
    EmojiEntry("❤️‍🔥", "heart_fire"),
    EmojiEntry("❤️‍🩹", "heart_mending"),
    EmojiEntry("⭐", "star"),
    EmojiEntry("🌟", "glowing_star"),
    EmojiEntry("💫", "star_dizzy"),
    EmojiEntry("☀️", "sun"),
    EmojiEntry("⛅", "partly_cloudy"),
    EmojiEntry("☁️", "cloud"),
    EmojiEntry("🌧️", "rain"),
    EmojiEntry("⛈️", "storm"),
    EmojiEntry("❄️", "snowflake"),
    EmojiEntry("🌪️", "tornado"),
    EmojiEntry("🌫️", "fog"),
    EmojiEntry("🌀", "cyclone"),
    EmojiEntry("🌈", "rainbow"),
    EmojiEntry("☂️", "umbrella"),
    EmojiEntry("⚡", "zap"),
    EmojiEntry("🌊", "ocean_wave"),
    EmojiEntry("💧", "droplet"),
    EmojiEntry("🔥", "fire2"),
    EmojiEntry("🌠", "shooting_star"),
    EmojiEntry("🌌", "milky_way"),
    EmojiEntry("♿", "accessible"),
    EmojiEntry("⚠️", "warning"),
    EmojiEntry("🚸", "crossing"),
    EmojiEntry("⛔", "no_entry"),
    EmojiEntry("🚫", "prohibited"),
    EmojiEntry("🚭", "no_smoking"),
    EmojiEntry("🔞", "18"),
    EmojiEntry("☢️", "radioactive"),
    EmojiEntry("☣️", "biohazard"),
    EmojiEntry("⬆️", "arrow_up"),
    EmojiEntry("↗️", "arrow_ne"),
    EmojiEntry("➡️", "arrow_right"),
    EmojiEntry("↘️", "arrow_se"),
    EmojiEntry("⬇️", "arrow_down"),
    EmojiEntry("↙️", "arrow_sw"),
    EmojiEntry("⬅️", "arrow_left"),
    EmojiEntry("↖️", "arrow_nw"),
    EmojiEntry("↕️", "arrow_v"),
    EmojiEntry("↔️", "arrow_h"),
    EmojiEntry("↩️", "arrow_return"),
    EmojiEntry("🔃", "arrows_clockwise"),
    EmojiEntry("🔄", "arrows_ccw"),
    EmojiEntry("🔙", "back"),
    EmojiEntry("🔝", "top"),
    EmojiEntry("🔚", "end"),
    EmojiEntry("🔜", "soon"),
    EmojiEntry("▶️", "play"),
    EmojiEntry("⏸️", "pause"),
    EmojiEntry("⏹️", "stop"),
    EmojiEntry("⏭️", "next"),
    EmojiEntry("⏮️", "previous"),
    EmojiEntry("⏏️", "eject"),
    EmojiEntry("🎬", "clapper"),
    EmojiEntry("📶", "signal"),
    EmojiEntry("🛜", "wifi"),
    EmojiEntry("♀️", "female"),
    EmojiEntry("♂️", "male"),
    EmojiEntry("✖️", "x"),
    EmojiEntry("➕", "plus"),
    EmojiEntry("➖", "minus"),
    EmojiEntry("➗", "divide"),
    EmojiEntry("🟰", "equals"),
    EmojiEntry("♾️", "infinity"),
    EmojiEntry("❓", "question"),
    EmojiEntry("❗", "exclamation"),
    EmojiEntry("⁉️", "interrobang"),
    EmojiEntry("♻️", "recycle"),
    EmojiEntry("🔱", "trident"),
    EmojiEntry("⭕", "circle_red"),
    EmojiEntry("✅", "check"),
    EmojiEntry("☑️", "checkbox"),
    EmojiEntry("✔️", "check2"),
    EmojiEntry("❌", "cross"),
    EmojiEntry("❎", "cross_button"),
    EmojiEntry("©️", "copyright"),
    EmojiEntry("®️", "registered"),
    EmojiEntry("™️", "tm"),
    EmojiEntry("#️⃣", "hash"),
    EmojiEntry("0️⃣", "zero"),
    EmojiEntry("1️⃣", "one"),
    EmojiEntry("2️⃣", "two"),
    EmojiEntry("3️⃣", "three"),
    EmojiEntry("4️⃣", "four"),
    EmojiEntry("5️⃣", "five"),
    EmojiEntry("6️⃣", "six"),
    EmojiEntry("7️⃣", "seven"),
    EmojiEntry("8️⃣", "eight"),
    EmojiEntry("9️⃣", "nine"),
    EmojiEntry("🔟", "ten"),
    EmojiEntry("🔴", "red_circle"),
    EmojiEntry("🟠", "orange_circle"),
    EmojiEntry("🟡", "yellow_circle"),
    EmojiEntry("🟢", "green_circle"),
    EmojiEntry("🔵", "blue_circle"),
    EmojiEntry("🟣", "purple_circle"),
    EmojiEntry("⚫", "black_circle"),
    EmojiEntry("⚪", "white_circle"),
    EmojiEntry("🟥", "red_square"),
    EmojiEntry("🟧", "orange_square"),
    EmojiEntry("🟨", "yellow_square"),
    EmojiEntry("🟩", "green_square"),
    EmojiEntry("🟦", "blue_square"),
    EmojiEntry("🟪", "purple_square"),
    EmojiEntry("⬛", "black_square"),
    EmojiEntry("⬜", "white_square"),
    EmojiEntry("🔶", "diamond_orange"),
    EmojiEntry("🔷", "diamond_blue"),
    EmojiEntry("🔺", "triangle_up"),
    EmojiEntry("🔻", "triangle_down"),
    EmojiEntry("💠", "diamond_dot"),
    EmojiEntry("🔘", "radio_button"),
    EmojiEntry("🔳", "sq_white"),
    EmojiEntry("🔲", "sq_black"),
)
